adminUser: admin
adminPassword: admin
defaultDashboardsTimezone: browser

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.31.192.111.254.sslip.io
  path: /
  pathType: Prefix

persistence:
  enabled: true
  size: 512Mi

resources:
  requests:
    cpu: 10m
    memory: 96Mi
  limits:
    cpu: 100m
    memory: 192Mi

sidecar:
  dashboards:
    enabled: true
    searchNamespace: monitoring
  datasources:
    enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        uid: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        jsonData:
          maxLines: 500

