fullnameOverride: kube-prometheus-stack

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  defaultDashboardsTimezone: browser
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.31.192.111.254.sslip.io
    path: /
    pathType: Prefix
  persistence:
    enabled: true
    size: 2Gi
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring
    datasources:
      enabled: true
      searchNamespace: monitoring
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      jsonData:
        maxLines: 1000

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
